services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: shopper
      POSTGRES_PASSWORD: shopper
      POSTGRES_DB: shopper
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: shopper
      POSTGRES_PASSWORD: shopper
      POSTGRES_DB: shopper
    shm_size: 128mb
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
